# Site settings
title: David Sasson
description: MS Data Sci HSPH
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "dsasson48.github.io"
# User settings
username: Data Science
user_description: MS Data Sci HSPH
user_title:  
email: dsasson[at]hsph.harvard.edu
#twitter_username: no
github_username:  dsasson48


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
